services:
  - type: web
    name: video-downloader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    branch: main
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7